"""Defaults for recommendations aggregation and discovery."""

DASHBOARD_ACTIVITY_LOOKBACK_DAYS = 30
DASHBOARD_GENRE_DISTRIBUTION_LIMIT = 10
DASHBOARD_PREFERENCE_ROW_LIMIT = 10
DASHBOARD_RECENT_INTERACTIONS_LIMIT = 10

DISCOVER_MIN_VOTE_COUNT_FOR_RECOMMENDATIONS = 100
DIRECTOR_FILMOGRAPHY_LIMIT = 10
BECAUSE_YOU_WATCHED_RECENT_INTERACTIONS = 5
BECAUSE_YOU_WATCHED_MOVIES_PER_TITLE = 5
