# Generated by Django 5.2.13 on 2026-04-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovieinteraction',
            name='poster_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
